
<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">CONTATO</h3>
            </div>
            <div class="panel-body">
                <p>
                    <form="formContato" name="formContato" action="<?php echo $this->url('contato'); ?>" method="POST">

                    Nome:<br/>
                    <input type="text" id="nome" name="nome"><br/>
                    Email:<br/>
                    <input type="text" id="email" name="email"><br/><br/> 
                    <input type="submit" id="btnEnviar" name="btnEnviar" value="Enviar">                
                    </form>
                </p>
        </div>
    </div>

</div>
